// <auto-generated />
using System;
using BZ2KMT_SOF_2023231.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BZ2KMT_SOF_2023231.Migrations
{
    [DbContext(typeof(SchollingDbContext))]
    [Migration("20250121180246_Ini")]
    partial class Ini
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BZ2KMT_SOF_2023231.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 0,
                            ImageFileName = "",
                            Name = "Sashegyi Arany János Gimnázium",
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Age = 0,
                            ImageFileName = "",
                            Name = "Katona József Szakközépiskola és Szakiskola",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 0,
                            ImageFileName = "",
                            Name = "Illyés Gyula Gimnázium",
                            Type = 0
                        });
                });

            modelBuilder.Entity("BZ2KMT_SOF_2023231.Models.SiteUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BZ2KMT_SOF_2023231.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("GradesAVG")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 16,
                            GradesAVG = 5.0,
                            Name = "Farkas Ádám",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 17,
                            GradesAVG = 3.2400000000000002,
                            Name = "Kiss Eszter",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 17,
                            GradesAVG = 4.7599999999999998,
                            Name = "Balogh Dóra",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 4,
                            Age = 13,
                            GradesAVG = 4.4530000000000003,
                            Name = "Molnár Levente",
                            SchoolId = 3
                        });
                });

            modelBuilder.Entity("BZ2KMT_SOF_2023231.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MainSubject")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MainSubject = 0,
                            Name = "Kovács Anna",
                            Salary = 270000,
                            SchoolId = 3
                        },
                        new
                        {
                            Id = 2,
                            MainSubject = 0,
                            Name = "Nagy Péter",
                            Salary = 245330,
                            SchoolId = 3
                        },
                        new
                        {
                            Id = 3,
                            MainSubject = 2,
                            Name = "Szabó Zsófia",
                            Salary = 400000,
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 4,
                            MainSubject = 3,
                            Name = "Tóth Bence",
                            Salary = 431000,
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 5,
                            MainSubject = 1,
                            Name = "Horváth Lilla",
                            Salary = 220000,
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 6,
                            MainSubject = 5,
                            Name = "Varga Gábor József",
                            Salary = 298000,
                            SchoolId = 2
                        });
                });

            modelBuilder.Entity("BZ2KMT_SOF_2023231.Models.Student", b =>
                {
                    b.HasOne("BZ2KMT_SOF_2023231.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("BZ2KMT_SOF_2023231.Models.Teacher", b =>
                {
                    b.HasOne("BZ2KMT_SOF_2023231.Models.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("BZ2KMT_SOF_2023231.Models.School", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
